<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="120566" started-at="2020-05-26T15:51:07Z" finished-at="2020-05-26T15:53:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="120566" started-at="2020-05-26T15:51:07Z" finished-at="2020-05-26T15:53:08Z">
      <class name="com.toolsqa.tests.Tutorial_linkTests">
        <test-method status="PASS" signature="tc_01()[pri:0, instance:com.toolsqa.tests.Tutorial_linkTests@26653222]" name="tc_01" duration-ms="99632" started-at="2020-05-26T15:51:08Z" finished-at="2020-05-26T15:52:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_01 -->
        <test-method status="FAIL" signature="tc_02()[pri:0, instance:com.toolsqa.tests.Tutorial_linkTests@26653222]" name="tc_02" duration-ms="20437" started-at="2020-05-26T15:52:48Z" depends-on-methods="com.toolsqa.tests.Tutorial_linkTests.tc_01" finished-at="2020-05-26T15:53:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[lists don't have the same size expected [7] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: lists don't have the same size expected [7] but found [1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:796)
at com.toolsqa.tests.Tutorial_linkTests.tc_02(Tutorial_linkTests.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_02 -->
      </class> <!-- com.toolsqa.tests.Tutorial_linkTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
